Improved error messages when an unknown contact ID is used in a command.
Handle the following error in `gam move drivefile`:
```
ERROR: 400: crossDomainMoveRestriction - Bad Request. User message: "crossDomainMoveRestriction"
```