Two fixes
Fixed bug in `gam <UserTypeEntity> print|show messages ... showbody` that caused a trap.
Added code to handle the following error that occurs when copying permissions:
```
ERROR: 400: shareInNotPermitted - Bad Request. User message: "An item can't be shared with user@domain.com because of domain.com sharing policy"