Fixed bug introduced in 6.29.15 that caused an error like this:
ERROR: Config File: gam.cfg, Section: DEFAULT, Item: todrive_locale, Value: "en_us", Expected: ,ar-eg,...