Multiple fixes/enhancements
Updated code to handle the following error when getting lists of students/teachers from courses.
```
ERROR: 503: serviceNotAvailable - The service is currently unavailable.
```

Fixed bug in `gam <UserTypeEntity> transfer drive <UserItem> select <DriveFileItem>` that caused files to be orphaned.

Added option `mergewithtarget` to `gam <UserTypeEntity> transfer drive <UserItem> select <DriveFileItem>`